// TODO: Replace mock data with real API when backend is available
// Multi-league match dataset — extends existing schedule data with club matches

import { ScheduleMatch } from "./scheduleData";

export const clubMatches: ScheduleMatch[] = [
  // ── Premier League ──
  {
    id: "epl-1",
    league: "Premier League",
    kickoffUtc: "15:00",
    kickoffLocal: "3:00 PM",
    kickoffDate: "Today",
    status: "LIVE",
    minute: 55,
    scoreHome: 2,
    scoreAway: 1,
    teamHome: "Arsenal",
    teamAway: "Liverpool",
    flagHome: "🔴",
    flagAway: "🔴",
    modelProbs: { home: 52.0, draw: 24.0, away: 24.0 },
    marketImplied: { home: 46.0, draw: 26.0, away: 28.0 },
    openMarketImplied: { home: 42.0, draw: 28.0, away: 30.0 },
    confidence: "High",
    edge: 6.0,
    edgeLabel: "Arsenal Win",
  },
  {
    id: "epl-2",
    league: "Premier League",
    kickoffUtc: "17:30",
    kickoffLocal: "5:30 PM",
    kickoffDate: "Today",
    status: "UPCOMING",
    minute: 0,
    scoreHome: 0,
    scoreAway: 0,
    teamHome: "Man City",
    teamAway: "Chelsea",
    flagHome: "🔵",
    flagAway: "🔵",
    modelProbs: { home: 55.0, draw: 22.0, away: 23.0 },
    marketImplied: { home: 50.0, draw: 24.0, away: 26.0 },
    openMarketImplied: { home: 48.0, draw: 25.0, away: 27.0 },
    confidence: "High",
    edge: 5.0,
    edgeLabel: "Man City Win",
  },

  // ── La Liga ──
  {
    id: "laliga-1",
    league: "La Liga",
    kickoffUtc: "20:00",
    kickoffLocal: "9:00 PM",
    kickoffDate: "Today",
    status: "UPCOMING",
    minute: 0,
    scoreHome: 0,
    scoreAway: 0,
    teamHome: "Real Madrid",
    teamAway: "Barcelona",
    flagHome: "⚪",
    flagAway: "🔵🔴",
    modelProbs: { home: 40.0, draw: 28.0, away: 32.0 },
    marketImplied: { home: 38.0, draw: 30.0, away: 32.0 },
    openMarketImplied: { home: 40.0, draw: 29.0, away: 31.0 },
    confidence: "Medium",
    edge: 2.0,
    edgeLabel: "Real Madrid Win",
  },
  {
    id: "laliga-2",
    league: "La Liga",
    kickoffUtc: "18:00",
    kickoffLocal: "7:00 PM",
    kickoffDate: "Tomorrow",
    status: "UPCOMING",
    minute: 0,
    scoreHome: 0,
    scoreAway: 0,
    teamHome: "Atlético Madrid",
    teamAway: "Sevilla",
    flagHome: "🔴⚪",
    flagAway: "⚪",
    modelProbs: { home: 52.0, draw: 26.0, away: 22.0 },
    marketImplied: { home: 46.0, draw: 28.0, away: 26.0 },
    openMarketImplied: { home: 45.0, draw: 28.0, away: 27.0 },
    confidence: "High",
    edge: 6.0,
    edgeLabel: "Atlético Win",
  },

  // ── Champions League ──
  {
    id: "ucl-1",
    league: "Champions League",
    kickoffUtc: "20:00",
    kickoffLocal: "9:00 PM",
    kickoffDate: "This Week",
    status: "UPCOMING",
    minute: 0,
    scoreHome: 0,
    scoreAway: 0,
    teamHome: "Bayern Munich",
    teamAway: "PSG",
    flagHome: "🔴",
    flagAway: "🔵",
    modelProbs: { home: 48.0, draw: 26.0, away: 26.0 },
    marketImplied: { home: 42.0, draw: 28.0, away: 30.0 },
    openMarketImplied: { home: 43.0, draw: 28.0, away: 29.0 },
    confidence: "High",
    edge: 6.0,
    edgeLabel: "Bayern Win",
  },
  {
    id: "ucl-2",
    league: "Champions League",
    kickoffUtc: "20:00",
    kickoffLocal: "9:00 PM",
    kickoffDate: "This Week",
    status: "UPCOMING",
    minute: 0,
    scoreHome: 0,
    scoreAway: 0,
    teamHome: "Inter Milan",
    teamAway: "Dortmund",
    flagHome: "🔵⚫",
    flagAway: "🟡",
    modelProbs: { home: 45.0, draw: 28.0, away: 27.0 },
    marketImplied: { home: 40.0, draw: 30.0, away: 30.0 },
    openMarketImplied: { home: 41.0, draw: 29.0, away: 30.0 },
    confidence: "Medium",
    edge: 5.0,
    edgeLabel: "Inter Win",
  },

  // ── Serie A ──
  {
    id: "seriea-1",
    league: "Serie A",
    kickoffUtc: "19:45",
    kickoffLocal: "8:45 PM",
    kickoffDate: "Tomorrow",
    status: "UPCOMING",
    minute: 0,
    scoreHome: 0,
    scoreAway: 0,
    teamHome: "Napoli",
    teamAway: "Juventus",
    flagHome: "🔵",
    flagAway: "⚪⚫",
    modelProbs: { home: 44.0, draw: 28.0, away: 28.0 },
    marketImplied: { home: 38.0, draw: 30.0, away: 32.0 },
    openMarketImplied: { home: 39.0, draw: 30.0, away: 31.0 },
    confidence: "High",
    edge: 6.0,
    edgeLabel: "Napoli Win",
  },

  // ── Bundesliga ──
  {
    id: "buli-1",
    league: "Bundesliga",
    kickoffUtc: "17:30",
    kickoffLocal: "6:30 PM",
    kickoffDate: "Tomorrow",
    status: "UPCOMING",
    minute: 0,
    scoreHome: 0,
    scoreAway: 0,
    teamHome: "Bayer Leverkusen",
    teamAway: "RB Leipzig",
    flagHome: "🔴",
    flagAway: "🔴⚪",
    modelProbs: { home: 50.0, draw: 26.0, away: 24.0 },
    marketImplied: { home: 44.0, draw: 28.0, away: 28.0 },
    openMarketImplied: { home: 43.0, draw: 28.0, away: 29.0 },
    confidence: "High",
    edge: 6.0,
    edgeLabel: "Leverkusen Win",
  },

  // ── Ligue 1 ──
  {
    id: "l1-1",
    league: "Ligue 1",
    kickoffUtc: "20:45",
    kickoffLocal: "9:45 PM",
    kickoffDate: "This Week",
    status: "UPCOMING",
    minute: 0,
    scoreHome: 0,
    scoreAway: 0,
    teamHome: "Marseille",
    teamAway: "Monaco",
    flagHome: "🔵⚪",
    flagAway: "🔴⚪",
    modelProbs: { home: 42.0, draw: 28.0, away: 30.0 },
    marketImplied: { home: 38.0, draw: 30.0, away: 32.0 },
    openMarketImplied: { home: 39.0, draw: 29.0, away: 32.0 },
    confidence: "Medium",
    edge: 4.0,
    edgeLabel: "Marseille Win",
  },

  // ── MLS ──
  {
    id: "mls-1",
    league: "MLS",
    kickoffUtc: "00:00",
    kickoffLocal: "8:00 PM",
    kickoffDate: "This Week",
    status: "UPCOMING",
    minute: 0,
    scoreHome: 0,
    scoreAway: 0,
    teamHome: "Inter Miami",
    teamAway: "LA Galaxy",
    flagHome: "🩷",
    flagAway: "🌟",
    modelProbs: { home: 48.0, draw: 26.0, away: 26.0 },
    marketImplied: { home: 42.0, draw: 28.0, away: 30.0 },
    openMarketImplied: { home: 41.0, draw: 29.0, away: 30.0 },
    confidence: "Medium",
    edge: 6.0,
    edgeLabel: "Inter Miami Win",
  },
];

// Helper to get all matches (schedule + club)
import { scheduleMatches } from "./scheduleData";

export const getAllMatches = (): ScheduleMatch[] => [...scheduleMatches, ...clubMatches];

// Map league display names to league IDs
const leagueNameToId: Record<string, string> = {
  "World Cup": "wc",
  "Qualifiers": "wc",
  "Friendlies": "wc",
  "Premier League": "epl",
  "La Liga": "laliga",
  "Serie A": "seriea",
  "Bundesliga": "bundesliga",
  "Ligue 1": "ligue1",
  "Champions League": "ucl",
  "MLS": "mls",
};

export const getLeagueIdFromName = (name: string): string => leagueNameToId[name] ?? "wc";

export const filterByLeague = (matches: ScheduleMatch[], leagueId: string): ScheduleMatch[] => {
  if (leagueId === "all") return matches;
  return matches.filter(m => getLeagueIdFromName(m.league) === leagueId);
};

export const getTopEdges = (matches: ScheduleMatch[], limit = 6): ScheduleMatch[] => {
  return [...matches].sort((a, b) => b.edge - a.edge).slice(0, limit);
};
