export interface ScheduleMatch {
  id: string;
  league: string;
  kickoffUtc: string;       // e.g. "14:00"
  kickoffLocal: string;     // e.g. "10:00 AM"
  kickoffDate: string;      // e.g. "Today", "Tomorrow", "Jun 20"
  status: "LIVE" | "UPCOMING";
  minute: number;           // only relevant when LIVE
  scoreHome: number;
  scoreAway: number;
  teamHome: string;
  teamAway: string;
  flagHome: string;
  flagAway: string;
  modelProbs: { home: number; draw: number; away: number };
  marketImplied: { home: number; draw: number; away: number };
  openMarketImplied: { home: number; draw: number; away: number };
  confidence: "High" | "Medium" | "Low";
  edge: number; // absolute best edge
  edgeLabel: string; // e.g. "Brazil Win"
  /** Maps to mockMatches id if available, for dashboard selection */
  linkedMatchId?: string;
}

export const scheduleMatches: ScheduleMatch[] = [
  // ── LIVE ──
  {
    id: "live-1",
    league: "World Cup",
    kickoffUtc: "18:00",
    kickoffLocal: "2:00 PM",
    kickoffDate: "Today",
    status: "LIVE",
    minute: 62,
    scoreHome: 1,
    scoreAway: 0,
    teamHome: "Brazil",
    teamAway: "Germany",
    flagHome: "🇧🇷",
    flagAway: "🇩🇪",
    modelProbs: { home: 58.4, draw: 22.1, away: 19.5 },
    marketImplied: { home: 52.0, draw: 24.0, away: 24.0 },
    openMarketImplied: { home: 48.0, draw: 26.0, away: 26.0 },
    confidence: "High",
    edge: 6.4,
    edgeLabel: "Brazil Win",
    linkedMatchId: "1",
  },
  {
    id: "live-2",
    league: "World Cup",
    kickoffUtc: "16:00",
    kickoffLocal: "12:00 PM",
    kickoffDate: "Today",
    status: "LIVE",
    minute: 78,
    scoreHome: 2,
    scoreAway: 2,
    teamHome: "Argentina",
    teamAway: "France",
    flagHome: "🇦🇷",
    flagAway: "🇫🇷",
    modelProbs: { home: 35.2, draw: 38.0, away: 26.8 },
    marketImplied: { home: 33.0, draw: 36.0, away: 31.0 },
    openMarketImplied: { home: 42.0, draw: 28.0, away: 30.0 },
    confidence: "Medium",
    edge: 2.2,
    edgeLabel: "Draw",
    linkedMatchId: "2",
  },
  {
    id: "live-3",
    league: "World Cup",
    kickoffUtc: "15:00",
    kickoffLocal: "11:00 AM",
    kickoffDate: "Today",
    status: "LIVE",
    minute: 34,
    scoreHome: 0,
    scoreAway: 1,
    teamHome: "Spain",
    teamAway: "England",
    flagHome: "🇪🇸",
    flagAway: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    modelProbs: { home: 30.0, draw: 28.0, away: 42.0 },
    marketImplied: { home: 34.0, draw: 30.0, away: 36.0 },
    openMarketImplied: { home: 38.0, draw: 30.0, away: 32.0 },
    confidence: "High",
    edge: 6.0,
    edgeLabel: "England Win",
    linkedMatchId: "3",
  },
  {
    id: "live-4",
    league: "Qualifiers",
    kickoffUtc: "14:00",
    kickoffLocal: "10:00 AM",
    kickoffDate: "Today",
    status: "LIVE",
    minute: 89,
    scoreHome: 3,
    scoreAway: 1,
    teamHome: "Italy",
    teamAway: "Croatia",
    flagHome: "🇮🇹",
    flagAway: "🇭🇷",
    modelProbs: { home: 88.0, draw: 8.0, away: 4.0 },
    marketImplied: { home: 85.0, draw: 10.0, away: 5.0 },
    openMarketImplied: { home: 55.0, draw: 25.0, away: 20.0 },
    confidence: "High",
    edge: 3.0,
    edgeLabel: "Italy Win",
  },
  {
    id: "live-5",
    league: "Friendlies",
    kickoffUtc: "17:00",
    kickoffLocal: "1:00 PM",
    kickoffDate: "Today",
    status: "LIVE",
    minute: 12,
    scoreHome: 0,
    scoreAway: 0,
    teamHome: "Japan",
    teamAway: "South Korea",
    flagHome: "🇯🇵",
    flagAway: "🇰🇷",
    modelProbs: { home: 44.0, draw: 30.0, away: 26.0 },
    marketImplied: { home: 40.0, draw: 32.0, away: 28.0 },
    openMarketImplied: { home: 41.0, draw: 31.0, away: 28.0 },
    confidence: "Medium",
    edge: 4.0,
    edgeLabel: "Japan Win",
  },
  // ── UPCOMING ──
  {
    id: "sched-1",
    league: "World Cup",
    kickoffUtc: "18:00",
    kickoffLocal: "2:00 PM",
    kickoffDate: "Today",
    status: "UPCOMING",
    minute: 0,
    scoreHome: 0,
    scoreAway: 0,
    teamHome: "Portugal",
    teamAway: "Netherlands",
    flagHome: "🇵🇹",
    flagAway: "🇳🇱",
    modelProbs: { home: 47.0, draw: 26.0, away: 27.0 },
    marketImplied: { home: 44.0, draw: 28.0, away: 28.0 },
    openMarketImplied: { home: 42.0, draw: 29.0, away: 29.0 },
    confidence: "Medium",
    edge: 3.0,
    edgeLabel: "Portugal Win",
    linkedMatchId: "4",
  },
  {
    id: "sched-2",
    league: "World Cup",
    kickoffUtc: "20:00",
    kickoffLocal: "4:00 PM",
    kickoffDate: "Today",
    status: "UPCOMING",
    minute: 0,
    scoreHome: 0,
    scoreAway: 0,
    teamHome: "Belgium",
    teamAway: "Uruguay",
    flagHome: "🇧🇪",
    flagAway: "🇺🇾",
    modelProbs: { home: 50.0, draw: 25.0, away: 25.0 },
    marketImplied: { home: 44.0, draw: 28.0, away: 28.0 },
    openMarketImplied: { home: 43.0, draw: 28.0, away: 29.0 },
    confidence: "High",
    edge: 6.0,
    edgeLabel: "Belgium Win",
  },
  {
    id: "sched-3",
    league: "Qualifiers",
    kickoffUtc: "14:00",
    kickoffLocal: "10:00 AM",
    kickoffDate: "Tomorrow",
    status: "UPCOMING",
    minute: 0,
    scoreHome: 0,
    scoreAway: 0,
    teamHome: "Mexico",
    teamAway: "USA",
    flagHome: "🇲🇽",
    flagAway: "🇺🇸",
    modelProbs: { home: 38.0, draw: 30.0, away: 32.0 },
    marketImplied: { home: 35.0, draw: 32.0, away: 33.0 },
    openMarketImplied: { home: 36.0, draw: 31.0, away: 33.0 },
    confidence: "Low",
    edge: 3.0,
    edgeLabel: "Mexico Win",
  },
  {
    id: "sched-4",
    league: "World Cup",
    kickoffUtc: "16:00",
    kickoffLocal: "12:00 PM",
    kickoffDate: "Tomorrow",
    status: "UPCOMING",
    minute: 0,
    scoreHome: 0,
    scoreAway: 0,
    teamHome: "Denmark",
    teamAway: "Switzerland",
    flagHome: "🇩🇰",
    flagAway: "🇨🇭",
    modelProbs: { home: 42.0, draw: 28.0, away: 30.0 },
    marketImplied: { home: 37.0, draw: 30.0, away: 33.0 },
    openMarketImplied: { home: 38.0, draw: 29.0, away: 33.0 },
    confidence: "Medium",
    edge: 5.0,
    edgeLabel: "Denmark Win",
  },
  {
    id: "sched-5",
    league: "Friendlies",
    kickoffUtc: "18:00",
    kickoffLocal: "2:00 PM",
    kickoffDate: "Tomorrow",
    status: "UPCOMING",
    minute: 0,
    scoreHome: 0,
    scoreAway: 0,
    teamHome: "Nigeria",
    teamAway: "Cameroon",
    flagHome: "🇳🇬",
    flagAway: "🇨🇲",
    modelProbs: { home: 45.0, draw: 28.0, away: 27.0 },
    marketImplied: { home: 40.0, draw: 30.0, away: 30.0 },
    openMarketImplied: { home: 39.0, draw: 30.0, away: 31.0 },
    confidence: "Medium",
    edge: 5.0,
    edgeLabel: "Nigeria Win",
  },
  {
    id: "sched-6",
    league: "World Cup",
    kickoffUtc: "20:00",
    kickoffLocal: "4:00 PM",
    kickoffDate: "This Week",
    status: "UPCOMING",
    minute: 0,
    scoreHome: 0,
    scoreAway: 0,
    teamHome: "Colombia",
    teamAway: "Chile",
    flagHome: "🇨🇴",
    flagAway: "🇨🇱",
    modelProbs: { home: 48.0, draw: 26.0, away: 26.0 },
    marketImplied: { home: 43.0, draw: 28.0, away: 29.0 },
    openMarketImplied: { home: 42.0, draw: 29.0, away: 29.0 },
    confidence: "Medium",
    edge: 5.0,
    edgeLabel: "Colombia Win",
  },
];
